name: auth_with_bloc
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

  #Firebase
  cloud_firestore: ^4.4.1
  firebase_analytics: ^10.1.6 
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_crashlytics: ^3.0.17
  firebase_messaging: ^14.3.0
  firebase_storage: ^11.0.16
  google_sign_in: ^6.0.2
  sign_in_with_apple: ^4.3.0

  #State Management
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  provider: ^6.0.2
  bloc_test: ^9.1.0
  mockito: ^5.3.2
  bloc_concurrency: ^0.2.0

  font_awesome_flutter: ^10.3.0
  fluentui_system_icons: ^1.1.153
  flutter_screenutil: ^5.0.4
  flutter_platform_widgets: ^3.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
